//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `StreamServerSlice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package StreamServerSlice;

/** @hidden */
public class _StreamIntPrxI extends com.zeroc.Ice._ObjectPrxI implements StreamIntPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
