//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `StreamServerSlice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package StreamServerSlice;

/**
 * Helper class for marshaling/unmarshaling SongSeq.
 **/
public final class SongSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, java.util.List<Song> v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.size());
            for(Song elem : v)
            {
                Song.ice_write(ostr, elem);
            }
        }
    }

    public static java.util.List<Song> read(com.zeroc.Ice.InputStream istr)
    {
        final java.util.List<Song> v;
        v = new java.util.ArrayList<Song>();
        final int len0 = istr.readAndCheckSeqSize(7);
        for(int i0 = 0; i0 < len0; i0++)
        {
            Song elem;
            elem = Song.ice_read(istr);
            v.add(elem);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<java.util.List<Song>> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.List<Song> v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            SongSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<java.util.List<Song>> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            java.util.List<Song> v;
            v = SongSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
